# Generated by uppr. Edit repos.conf, then run `uppr generate`.
FROM caddy:2-builder AS builder

RUN xcaddy build --with github.com/mholt/caddy-ratelimit@latest

FROM caddy:2-alpine

COPY --from=builder /usr/bin/caddy /usr/bin/caddy
