package main

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"
)

const (
	caddyFile         = "Caddyfile"
	caddyDockerFile   = "caddyx.Dockerfile"
	dockerComposeFile = "docker-compose.yml"
	makeFile          = "Makefile"
)

func generateProjectFiles() error {
	root, err := findProjectRoot(".")
	if err != nil {
		return err
	}
	return generateProjectFilesAt(root)
}

func generateServerFilesAt(root string) error {
	if err := writeServerFilesAt(root); err != nil {
		return err
	}
	fmt.Printf("generated master %s, %s, %s, and %s\n", caddyFile, caddyDockerFile, dockerComposeFile, makeFile)
	return nil
}

func writeServerFilesAt(root string) error {
	values, err := readDotEnv(filepath.Join(root, envFile))
	if err != nil {
		return err
	}
	workspaces, err := readWorkspaces(filepath.Join(root, workspacesFile))
	if err != nil {
		return err
	}
	services, err := collectServerServices(root, workspaces)
	if err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(root, caddyFile), []byte(renderServerCaddyfile(services, envList(values["UPPR_DOMAINS"]), upprRateLimitFromEnv(values))), 0o600); err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(root, caddyDockerFile), []byte(renderCaddyDockerfile()), 0o600); err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(root, dockerComposeFile), []byte(renderServerDockerCompose(root, services)), 0o600); err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(root, makeFile), []byte(renderServerMakefile(workspaces)), 0o600); err != nil {
		return err
	}
	return nil
}

type serverService struct {
	Workspace Workspace
	Root      string
	Repo      Repo
	Service   string
}

func collectServerServices(root string, workspaces []Workspace) ([]serverService, error) {
	var services []serverService
	seen := map[string]int{}
	for _, workspace := range workspaces {
		workspaceRoot := workspace.Path
		if !filepath.IsAbs(workspaceRoot) {
			workspaceRoot = filepath.Join(root, workspaceRoot)
		}
		repos, err := readRepos(filepath.Join(workspaceRoot, reposFile))
		if err != nil {
			return nil, fmt.Errorf("%s: %w", workspace.Name, err)
		}
		if err := applyDockerfileExposedPorts(workspaceRoot, repos); err != nil {
			return nil, fmt.Errorf("%s: %w", workspace.Name, err)
		}
		for _, repo := range repos {
			base := serviceName(Repo{Name: workspace.Name + "-" + serviceName(repo)})
			seen[base]++
			name := base
			if seen[base] > 1 {
				name = fmt.Sprintf("%s-%d", base, seen[base])
			}
			services = append(services, serverService{
				Workspace: workspace,
				Root:      workspaceRoot,
				Repo:      repo,
				Service:   name,
			})
		}
	}
	return services, nil
}

func generateProjectFilesAt(root string) error {
	repos, err := readRepos(filepath.Join(root, reposFile))
	if err != nil {
		return err
	}
	if len(repos) == 0 {
		return fmt.Errorf("%s does not contain any repos", filepath.Join(root, reposFile))
	}
	if err := applyDockerfileExposedPorts(root, repos); err != nil {
		return err
	}

	if err := os.WriteFile(filepath.Join(root, caddyFile), []byte(renderCaddyfile(repos)), 0o600); err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(root, caddyDockerFile), []byte(renderCaddyDockerfile()), 0o600); err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(root, dockerComposeFile), []byte(renderDockerCompose(root, repos)), 0o600); err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(root, makeFile), []byte(renderMakefile()), 0o600); err != nil {
		return err
	}
	fmt.Printf("generated %s, %s, %s, and %s\n", caddyFile, caddyDockerFile, dockerComposeFile, makeFile)
	return nil
}

func applyDockerfileExposedPorts(root string, repos []Repo) error {
	resolvedRepos := append([]Repo(nil), repos...)
	resolveRepoPaths(root, resolvedRepos)
	for i := range repos {
		if repos[i].Port != 0 && repos[i].ContainerPort != 0 {
			continue
		}
		port, err := readDockerfileExposedPort(filepath.Join(resolvedRepos[i].Path, "Dockerfile"))
		if err != nil {
			return err
		}
		if port != 0 {
			if repos[i].Port == 0 {
				repos[i].Port = port
			}
			if repos[i].ContainerPort == 0 {
				repos[i].ContainerPort = port
			}
		}
	}
	return nil
}

func renderCaddyfile(repos []Repo) string {
	var builder strings.Builder
	builder.WriteString("# Generated by uppr. Edit repos.conf, then run `uppr generate`.\n\n")
	for _, repo := range repos {
		targetPort := repo.ContainerPort
		if targetPort == 0 {
			targetPort = repo.Port
		}
		if targetPort == 0 {
			continue
		}
		fmt.Fprintf(&builder, "%s {\n", strings.Join(repoDomains(repo), " "))
		rateLimit := normalizeRateLimit(repo.RateLimit)
		if rateLimit.Enabled {
			builder.WriteString("\trate_limit {\n")
			fmt.Fprintf(&builder, "\t\tzone %s {\n", rateLimit.Zone)
			builder.WriteString("\t\t\tkey {remote_host}\n")
			fmt.Fprintf(&builder, "\t\t\tevents %d\n", rateLimit.Events)
			fmt.Fprintf(&builder, "\t\t\twindow %s\n", rateLimit.Window)
			builder.WriteString("\t\t}\n")
			builder.WriteString("\t}\n")
		}
		fmt.Fprintf(&builder, "\treverse_proxy %s:%d\n", serviceName(repo), targetPort)
		builder.WriteString("}\n\n")
	}
	return builder.String()
}

func renderCaddyDockerfile() string {
	return `# Generated by uppr. Edit repos.conf, then run ` + "`uppr generate`" + `.
FROM caddy:2-builder AS builder

RUN xcaddy build --with github.com/mholt/caddy-ratelimit@latest

FROM caddy:2-alpine

COPY --from=builder /usr/bin/caddy /usr/bin/caddy
`
}

func renderDockerCompose(root string, repos []Repo) string {
	var builder strings.Builder
	builder.WriteString("# Generated by uppr. Edit repos.conf, then run `uppr generate`.\n")
	builder.WriteString("services:\n")
	builder.WriteString("  caddy:\n")
	builder.WriteString("    build:\n")
	builder.WriteString("      context: .\n")
	fmt.Fprintf(&builder, "      dockerfile: %s\n", caddyDockerFile)
	builder.WriteString("    image: uppr-caddyx:latest\n")
	builder.WriteString("    restart: unless-stopped\n")
	builder.WriteString("    ports:\n")
	builder.WriteString("      - \"80:80\"\n")
	builder.WriteString("      - \"443:443\"\n")
	builder.WriteString("    volumes:\n")
	builder.WriteString("      - ./Caddyfile:/etc/caddy/Caddyfile:ro\n")
	builder.WriteString("      - caddy_data:/data\n")
	builder.WriteString("      - caddy_config:/config\n")

	for _, repo := range repos {
		builder.WriteString("\n")
		name := serviceName(repo)
		fmt.Fprintf(&builder, "  %s:\n", name)
		fmt.Fprintf(&builder, "    build:\n")
		fmt.Fprintf(&builder, "      context: %s\n", composeContextPath(root, repo.Path))
		builder.WriteString("    restart: unless-stopped\n")
		builder.WriteString("    env_file:\n")
		fmt.Fprintf(&builder, "      - %s\n", composeRepoPath(root, repo.Path, "config", ".env"))
		if repo.Port != 0 {
			targetPort := repo.ContainerPort
			if targetPort == 0 {
				targetPort = repo.Port
			}
			builder.WriteString("    ports:\n")
			fmt.Fprintf(&builder, "      - \"%d:%d\"\n", repo.Port, targetPort)
		}
		if len(repo.Env) > 0 {
			builder.WriteString("    environment:\n")
			for _, entry := range repo.Env {
				key, value, ok := strings.Cut(entry, "=")
				if !ok {
					fmt.Fprintf(&builder, "      - %q\n", entry)
					continue
				}
				fmt.Fprintf(&builder, "      %s: %q\n", key, value)
			}
		}
		builder.WriteString("    volumes:\n")
		fmt.Fprintf(&builder, "      - %q\n", composeRepoPath(root, repo.Path, "config")+":/app/config")
		fmt.Fprintf(&builder, "      - %q\n", composeRepoPath(root, repo.Path, "data")+":/app/data")
		for _, volume := range repo.Volumes {
			if isProtectedAppVolume(volume) {
				continue
			}
			fmt.Fprintf(&builder, "      - %q\n", volume)
		}
	}

	builder.WriteString("\nvolumes:\n")
	builder.WriteString("  caddy_data:\n")
	builder.WriteString("  caddy_config:\n")
	return builder.String()
}

func composeContextPath(root, repoPath string) string {
	if filepath.IsAbs(repoPath) {
		if rel, err := filepath.Rel(root, repoPath); err == nil && rel != ".." && !strings.HasPrefix(rel, ".."+string(filepath.Separator)) {
			repoPath = rel
		} else {
			return filepath.ToSlash(repoPath)
		}
	}
	return "./" + filepath.ToSlash(repoPath)
}

func composeRepoPath(root, repoPath string, elems ...string) string {
	if repoPath == "" {
		repoPath = "."
	}
	parts := append([]string{repoPath}, elems...)
	return composeContextPath(root, filepath.Join(parts...))
}

func isProtectedAppVolume(volume string) bool {
	parts := strings.Split(volume, ":")
	if len(parts) < 2 {
		return false
	}
	target := parts[1]
	return target == "/app/config" || target == "/app/data"
}

func renderMakefile() string {
	return `.PHONY: generate launch stop pull push

generate:
	uppr generate

launch: generate
	docker compose down --remove-orphans
	docker compose up --build

stop:
	docker compose down

pull:
	uppr pull

push:
	@test -n "$(m)" || (echo 'usage: make push m="commit message"' && exit 1)
	uppr push "$(m)"
`
}

func renderServerCaddyfile(services []serverService, upprDomains []string, upprRateLimit RateLimit) string {
	var builder strings.Builder
	builder.WriteString("# Generated by uppr. Edit workspace repos.conf files, then run `uppr generate-server`.\n\n")
	if len(upprDomains) > 0 {
		fmt.Fprintf(&builder, "%s {\n", strings.Join(upprDomains, " "))
		writeCaddyRateLimit(&builder, upprRateLimit)
		builder.WriteString("\treverse_proxy uppr:9944\n}\n\n")
	}
	for _, service := range services {
		repo := service.Repo
		targetPort := repo.ContainerPort
		if targetPort == 0 {
			targetPort = repo.Port
		}
		if targetPort == 0 {
			continue
		}
		fmt.Fprintf(&builder, "%s {\n", strings.Join(repoDomains(repo), " "))
		rateLimit := normalizeRateLimit(repo.RateLimit)
		writeCaddyRateLimit(&builder, rateLimit)
		fmt.Fprintf(&builder, "\treverse_proxy %s:%d\n", service.Service, targetPort)
		builder.WriteString("}\n\n")
	}
	return builder.String()
}

func renderServerDockerCompose(root string, services []serverService) string {
	var builder strings.Builder
	builder.WriteString("# Generated by uppr. Edit workspace repos.conf files, then run `uppr generate-server`.\n")
	builder.WriteString("services:\n")
	builder.WriteString("  uppr:\n")
	builder.WriteString("    build:\n")
	builder.WriteString("      context: .\n")
	builder.WriteString("    image: ${UPPR_DOCKER_IMAGE:-uppr:local}\n")
	builder.WriteString("    restart: unless-stopped\n")
	builder.WriteString("    env_file:\n")
	builder.WriteString("      - ./config/.env\n")
	fmt.Fprintf(&builder, "    working_dir: %s\n", strconv.Quote(filepath.ToSlash(root)))
	fmt.Fprintf(&builder, "    command: [\"uppr\", \"serve\", \"--addr\", \"0.0.0.0:9944\", %s]\n", strconv.Quote(filepath.ToSlash(root)))
	builder.WriteString("    volumes:\n")
	fmt.Fprintf(&builder, "      - %q\n", filepath.ToSlash(root)+":"+filepath.ToSlash(root))
	mountedRoots := map[string]bool{filepath.Clean(root): true}
	for _, service := range services {
		workspaceRoot := filepath.Clean(service.Root)
		if mountedRoots[workspaceRoot] {
			continue
		}
		mountedRoots[workspaceRoot] = true
		fmt.Fprintf(&builder, "      - %q\n", filepath.ToSlash(workspaceRoot)+":"+filepath.ToSlash(workspaceRoot))
	}
	builder.WriteString("      - /var/run/docker.sock:/var/run/docker.sock\n")
	builder.WriteString("    networks:\n")
	builder.WriteString("      - default\n")
	builder.WriteString("\n")
	builder.WriteString("  caddy:\n")
	builder.WriteString("    depends_on:\n")
	builder.WriteString("      - uppr\n")
	builder.WriteString("    build:\n")
	builder.WriteString("      context: .\n")
	fmt.Fprintf(&builder, "      dockerfile: %s\n", caddyDockerFile)
	builder.WriteString("    image: uppr-caddyx:latest\n")
	builder.WriteString("    restart: unless-stopped\n")
	builder.WriteString("    ports:\n")
	builder.WriteString("      - \"80:80\"\n")
	builder.WriteString("      - \"443:443\"\n")
	builder.WriteString("    volumes:\n")
	builder.WriteString("      - ./Caddyfile:/etc/caddy/Caddyfile:ro\n")
	builder.WriteString("      - caddy_data:/data\n")
	builder.WriteString("      - caddy_config:/config\n")
	builder.WriteString("    networks:\n")
	builder.WriteString("      - default\n")

	for _, service := range services {
		repo := service.Repo
		builder.WriteString("\n")
		fmt.Fprintf(&builder, "  %s:\n", service.Service)
		builder.WriteString("    build:\n")
		fmt.Fprintf(&builder, "      context: %s\n", composePath(root, filepath.Join(service.Root, repo.Path)))
		builder.WriteString("    restart: unless-stopped\n")
		builder.WriteString("    env_file:\n")
		fmt.Fprintf(&builder, "      - %s\n", composePath(root, filepath.Join(service.Root, repo.Path, "config", ".env")))
		if len(repo.Env) > 0 {
			builder.WriteString("    environment:\n")
			for _, entry := range repo.Env {
				key, value, ok := strings.Cut(entry, "=")
				if !ok {
					fmt.Fprintf(&builder, "      - %q\n", entry)
					continue
				}
				fmt.Fprintf(&builder, "      %s: %q\n", key, value)
			}
		}
		builder.WriteString("    volumes:\n")
		fmt.Fprintf(&builder, "      - %q\n", composeVolumePath(root, filepath.Join(service.Root, repo.Path, "config"), "/app/config"))
		fmt.Fprintf(&builder, "      - %q\n", composeVolumePath(root, filepath.Join(service.Root, repo.Path, "data"), "/app/data"))
		for _, volume := range repo.Volumes {
			if isProtectedAppVolume(volume) {
				continue
			}
			fmt.Fprintf(&builder, "      - %q\n", volume)
		}
	}

	builder.WriteString("\nvolumes:\n")
	builder.WriteString("  caddy_data:\n")
	builder.WriteString("  caddy_config:\n")
	builder.WriteString("\nnetworks:\n")
	builder.WriteString("  default:\n")
	builder.WriteString("    external: true\n")
	builder.WriteString("    name: ${UPPR_DOCKER_NETWORK:-uppr-network}\n")
	return builder.String()
}

func envList(value string) []string {
	return strings.FieldsFunc(value, func(r rune) bool { return r == ',' || r == ' ' || r == '\t' })
}

func upprRateLimitFromEnv(values map[string]string) RateLimit {
	zone := strings.TrimSpace(values["UPPR_RATE_LIMIT_ZONE"])
	if zone == "" {
		zone = "uppr"
	}
	rateLimit := RateLimit{
		Enabled: true,
		Zone:    zone,
		Window:  strings.TrimSpace(values["UPPR_RATE_LIMIT_WINDOW"]),
	}
	rateLimit.Events, _ = strconv.Atoi(strings.TrimSpace(values["UPPR_RATE_LIMIT_EVENTS"]))
	if value := strings.TrimSpace(values["UPPR_RATE_LIMIT_ENABLED"]); value != "" {
		if enabled, err := strconv.ParseBool(value); err == nil {
			rateLimit.Enabled = enabled
		}
	}
	return normalizeRateLimit(rateLimit)
}

func writeCaddyRateLimit(builder *strings.Builder, rateLimit RateLimit) {
	rateLimit = normalizeRateLimit(rateLimit)
	if !rateLimit.Enabled {
		return
	}
	builder.WriteString("\trate_limit {\n")
	fmt.Fprintf(builder, "\t\tzone %s {\n", rateLimit.Zone)
	builder.WriteString("\t\t\tkey {remote_host}\n")
	fmt.Fprintf(builder, "\t\t\tevents %d\n", rateLimit.Events)
	fmt.Fprintf(builder, "\t\t\twindow %s\n", rateLimit.Window)
	builder.WriteString("\t\t}\n")
	builder.WriteString("\t}\n")
}

func composePath(root, path string) string {
	return strconv.Quote(composeContextPath(root, path))
}

func composeVolumePath(root, source, target string) string {
	return composeContextPath(root, source) + ":" + target
}

func renderServerMakefile(workspaces []Workspace) string {
	var builder strings.Builder
	builder.WriteString(".PHONY: generate launch stop pull push\n\n")
	builder.WriteString(`generate:
	uppr generate-server

launch: generate
	services="$$(docker compose config --services | grep -v '^uppr$$')" && docker compose up --build -d --remove-orphans --no-deps $$services

stop:
	docker compose down

pull:
`)
	if len(workspaces) == 0 {
		builder.WriteString("\t@echo 'no workspaces configured'\n")
	} else {
		for _, workspace := range workspaces {
			fmt.Fprintf(&builder, "\t@if [ -f %s ]; then (cd %s && uppr pull); fi\n", shellQuote(filepath.Join(workspace.Path, reposFile)), shellQuote(workspace.Path))
		}
	}
	builder.WriteString(`

push:
	@test -n "$(m)" || (echo 'usage: make push m="commit message"' && exit 1)
`)
	if len(workspaces) == 0 {
		builder.WriteString("\t@echo 'no workspaces configured'\n")
	} else {
		for _, workspace := range workspaces {
			fmt.Fprintf(&builder, "\t@if [ -f %s ]; then (cd %s && uppr push \"$(m)\"); fi\n", shellQuote(filepath.Join(workspace.Path, reposFile)), shellQuote(workspace.Path))
		}
	}
	return builder.String()
}

var nonServiceName = regexp.MustCompile(`[^a-zA-Z0-9_-]+`)

func serviceName(repo Repo) string {
	name := repo.Name
	if name == "" {
		name = repoNameFromURL(repo.URL)
	}
	name = strings.Trim(nonServiceName.ReplaceAllString(name, "-"), "-_")
	if name == "" {
		name = "app"
	}
	return strings.ToLower(name)
}
