package main

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

const (
	caddyFile         = "Caddyfile"
	caddyDockerFile   = "caddyx.Dockerfile"
	dockerComposeFile = "docker-compose.yml"
	makeFile          = "Makefile"
)

func generateProjectFiles() error {
	root, err := findProjectRoot(".")
	if err != nil {
		return err
	}
	return generateProjectFilesAt(root)
}

func generateServerFilesAt(root string) error {
	workspaces, err := readWorkspaces(filepath.Join(root, workspacesFile))
	if err != nil {
		return err
	}
	for _, workspace := range workspaces {
		workspaceRoot := workspace.Path
		if !filepath.IsAbs(workspaceRoot) {
			workspaceRoot = filepath.Join(root, workspaceRoot)
		}
		if err := generateProjectFilesAt(workspaceRoot); err != nil {
			return fmt.Errorf("%s: %w", workspace.Name, err)
		}
	}
	if err := os.WriteFile(filepath.Join(root, dockerComposeFile), []byte(renderServerDockerCompose(workspaces)), 0o600); err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(root, makeFile), []byte(renderServerMakefile()), 0o600); err != nil {
		return err
	}
	fmt.Printf("generated master %s and %s\n", dockerComposeFile, makeFile)
	return nil
}

func generateProjectFilesAt(root string) error {
	repos, err := readRepos(filepath.Join(root, reposFile))
	if err != nil {
		return err
	}
	if len(repos) == 0 {
		return fmt.Errorf("%s does not contain any repos", filepath.Join(root, reposFile))
	}
	if err := applyDockerfileExposedPorts(root, repos); err != nil {
		return err
	}

	if err := os.WriteFile(filepath.Join(root, caddyFile), []byte(renderCaddyfile(repos)), 0o600); err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(root, caddyDockerFile), []byte(renderCaddyDockerfile()), 0o600); err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(root, dockerComposeFile), []byte(renderDockerCompose(root, repos)), 0o600); err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(root, makeFile), []byte(renderMakefile()), 0o600); err != nil {
		return err
	}
	fmt.Printf("generated %s, %s, %s, and %s\n", caddyFile, caddyDockerFile, dockerComposeFile, makeFile)
	return nil
}

func applyDockerfileExposedPorts(root string, repos []Repo) error {
	resolvedRepos := append([]Repo(nil), repos...)
	resolveRepoPaths(root, resolvedRepos)
	for i := range repos {
		if repos[i].ContainerPort != 0 {
			continue
		}
		port, err := readDockerfileExposedPort(filepath.Join(resolvedRepos[i].Path, "Dockerfile"))
		if err != nil {
			return err
		}
		if port != 0 {
			repos[i].ContainerPort = port
		}
	}
	return nil
}

func renderCaddyfile(repos []Repo) string {
	var builder strings.Builder
	builder.WriteString("# Generated by uppr. Edit repos.conf, then run `uppr generate`.\n\n")
	for _, repo := range repos {
		targetPort := repo.ContainerPort
		if targetPort == 0 {
			targetPort = repo.Port
		}
		if targetPort == 0 {
			continue
		}
		fmt.Fprintf(&builder, "%s {\n", strings.Join(repoDomains(repo), " "))
		rateLimit := normalizeRateLimit(repo.RateLimit)
		if rateLimit.Enabled {
			builder.WriteString("\trate_limit {\n")
			fmt.Fprintf(&builder, "\t\tzone %s {\n", rateLimit.Zone)
			builder.WriteString("\t\t\tkey {remote_host}\n")
			fmt.Fprintf(&builder, "\t\t\tevents %d\n", rateLimit.Events)
			fmt.Fprintf(&builder, "\t\t\twindow %s\n", rateLimit.Window)
			builder.WriteString("\t\t}\n")
			builder.WriteString("\t}\n")
		}
		fmt.Fprintf(&builder, "\treverse_proxy %s:%d\n", serviceName(repo), targetPort)
		builder.WriteString("}\n\n")
	}
	return builder.String()
}

func renderCaddyDockerfile() string {
	return `# Generated by uppr. Edit repos.conf, then run ` + "`uppr generate`" + `.
FROM caddy:2-builder AS builder

RUN xcaddy build --with github.com/mholt/caddy-ratelimit@latest

FROM caddy:2-alpine

COPY --from=builder /usr/bin/caddy /usr/bin/caddy
`
}

func renderDockerCompose(root string, repos []Repo) string {
	var builder strings.Builder
	builder.WriteString("# Generated by uppr. Edit repos.conf, then run `uppr generate`.\n")
	builder.WriteString("services:\n")
	builder.WriteString("  caddy:\n")
	builder.WriteString("    build:\n")
	builder.WriteString("      context: .\n")
	fmt.Fprintf(&builder, "      dockerfile: %s\n", caddyDockerFile)
	builder.WriteString("    image: uppr-caddyx:latest\n")
	builder.WriteString("    restart: unless-stopped\n")
	builder.WriteString("    ports:\n")
	builder.WriteString("      - \"80:80\"\n")
	builder.WriteString("      - \"443:443\"\n")
	builder.WriteString("    volumes:\n")
	builder.WriteString("      - ./Caddyfile:/etc/caddy/Caddyfile:ro\n")
	builder.WriteString("      - caddy_data:/data\n")
	builder.WriteString("      - caddy_config:/config\n")

	for _, repo := range repos {
		builder.WriteString("\n")
		name := serviceName(repo)
		fmt.Fprintf(&builder, "  %s:\n", name)
		fmt.Fprintf(&builder, "    build:\n")
		fmt.Fprintf(&builder, "      context: %s\n", composeContextPath(root, repo.Path))
		builder.WriteString("    restart: unless-stopped\n")
		builder.WriteString("    env_file:\n")
		fmt.Fprintf(&builder, "      - %s\n", composeRepoPath(root, repo.Path, "config", ".env"))
		if repo.Port != 0 {
			targetPort := repo.ContainerPort
			if targetPort == 0 {
				targetPort = repo.Port
			}
			builder.WriteString("    ports:\n")
			fmt.Fprintf(&builder, "      - \"%d:%d\"\n", repo.Port, targetPort)
		}
		if len(repo.Env) > 0 {
			builder.WriteString("    environment:\n")
			for _, entry := range repo.Env {
				key, value, ok := strings.Cut(entry, "=")
				if !ok {
					fmt.Fprintf(&builder, "      - %q\n", entry)
					continue
				}
				fmt.Fprintf(&builder, "      %s: %q\n", key, value)
			}
		}
		builder.WriteString("    volumes:\n")
		fmt.Fprintf(&builder, "      - %q\n", composeRepoPath(root, repo.Path, "config")+":/app/config")
		fmt.Fprintf(&builder, "      - %q\n", composeRepoPath(root, repo.Path, "data")+":/app/data")
		for _, volume := range repo.Volumes {
			if isProtectedAppVolume(volume) {
				continue
			}
			fmt.Fprintf(&builder, "      - %q\n", volume)
		}
	}

	builder.WriteString("\nvolumes:\n")
	builder.WriteString("  caddy_data:\n")
	builder.WriteString("  caddy_config:\n")
	return builder.String()
}

func composeContextPath(root, repoPath string) string {
	if filepath.IsAbs(repoPath) {
		if rel, err := filepath.Rel(root, repoPath); err == nil && rel != ".." && !strings.HasPrefix(rel, ".."+string(filepath.Separator)) {
			repoPath = rel
		} else {
			return filepath.ToSlash(repoPath)
		}
	}
	return "./" + filepath.ToSlash(repoPath)
}

func composeRepoPath(root, repoPath string, elems ...string) string {
	if repoPath == "" {
		repoPath = "."
	}
	parts := append([]string{repoPath}, elems...)
	return composeContextPath(root, filepath.Join(parts...))
}

func isProtectedAppVolume(volume string) bool {
	parts := strings.Split(volume, ":")
	if len(parts) < 2 {
		return false
	}
	target := parts[1]
	return target == "/app/config" || target == "/app/data"
}

func renderMakefile() string {
	return `.PHONY: generate launch stop pull push

generate:
	uppr generate

launch: generate
	docker compose up --build

stop:
	docker compose down

pull:
	uppr pull

push:
	@test -n "$(m)" || (echo 'usage: make push m="commit message"' && exit 1)
	uppr push "$(m)"
`
}

func renderServerDockerCompose(workspaces []Workspace) string {
	var builder strings.Builder
	builder.WriteString("# Generated by uppr. Workspaces include their own compose files.\n")
	if len(workspaces) == 0 {
		builder.WriteString("services: {}\n")
		return builder.String()
	}
	builder.WriteString("include:\n")
	for _, workspace := range workspaces {
		fmt.Fprintf(&builder, "  - %s\n", filepath.ToSlash(filepath.Join(workspace.Path, dockerComposeFile)))
	}
	return builder.String()
}

func renderServerMakefile() string {
	return `.PHONY: generate launch stop pull push

generate:
	uppr generate-server

launch: generate
	docker compose up --build

stop:
	docker compose down

pull:
	@for workspace in workspaces/*; do \
		if [ -f "$$workspace/repos.conf" ]; then (cd "$$workspace" && uppr pull); fi; \
	done

push:
	@test -n "$(m)" || (echo 'usage: make push m="commit message"' && exit 1)
	@for workspace in workspaces/*; do \
		if [ -f "$$workspace/repos.conf" ]; then (cd "$$workspace" && uppr push "$(m)"); fi; \
	done
`
}

var nonServiceName = regexp.MustCompile(`[^a-zA-Z0-9_-]+`)

func serviceName(repo Repo) string {
	name := repo.Name
	if name == "" {
		name = repoNameFromURL(repo.URL)
	}
	name = strings.Trim(nonServiceName.ReplaceAllString(name, "-"), "-_")
	if name == "" {
		name = "app"
	}
	return strings.ToLower(name)
}
